package com.visa.commons;

public final class Constants {

	public static String SP_OBTENERCARRERASPOSTGRADO = "PKG_PAGOVISA.SP_OBTENERCARRERASPOSTGRADO";
	public static String SP_OBTENERCARRERASPOSTULANTE = "PKG_PAGOVISA.SP_OBTENERCARRERASPOSTULANTE";
	public static String SP_OBTENERCARRERASPROSPECTO = "PKG_PAGOVISA.SP_OBTENERCARRERASPROSPECTO";
	public static String SPS_CUOTASACTUALES = "PKG_PAGOVISA.SPS_CUOTASACTUALES";
	public static String SPS_LISTARCUOTASPOSTULANTE = "PKG_PAGOVISA.SPS_LISTARCUOTASPOSTULANTE";
	public static String SPS_LISTARCUOTASPROSPECTO = "PKG_PAGOVISA.SPS_LISTARCUOTASPROSPECTO";

	public static String PS_ALUMNO = "PS_ALUMNO";
	public static String PS_POSTULANTE = "PS_POSTULANTE";
	public static String PS_CARRERA = "PS_CARRERA";
	
	public static String PS_PROSPECTO = "PS_PROSPECTO";
	public static String PS_ATENCION = "PS_ATENCION";

	
	public static String P_CURSOR = "pCursor";

}
